### PR TITLE
SLING-10294: CLI Status Code

### PR DESCRIPTION
**Pull request by klcodanr**
Make the commands Callable<Integer> to have them return a status code to the shell. For example:
Screen Shot 2021-04-12 at 9 00 58 AM

### CODE REVIEW

**Review by raducotescu — APPROVED** [review]

**Review by rombert — COMMENTED** [review]
I think it's going in the right direction but returning 'naked' Integers seems wrong. A couple of options that I see for improving this:
- return true/false and set the return code accordingly
- propagate exceptions
- use constants instead of return values
- use enums which encapsulate the return codes.

**Comment by klcodanr** [comment]
@rombert - Good point, IMO enums seem to be the best option. I want to be able to differentiate between successful runs, unsuccessful runs (ex: a release which is not valid) and failed runs (ex: validating a release that does not exist)

**Comment by klcodanr** [comment]
@rombert - I spoke too soon, Picocli has built-in [exit code constants](https://picocli.info/#_exception_exit_codes), so rather than creating separate enum / constant, I think it makes sense to use those.

**Review by rombert — APPROVED** [review]
LGTM, thanks. Maybe you can also document this convention on the `Command` interface. Can be a follow-up commit, should not block the merge.

**Pull request merged**
