### PR TITLE
SLING-8519 - Improve CLI parsing and general look and feel

### PR DESCRIPTION
**Pull request by raducotescu**
* embedded picocli.CommandLine version 4.0.0-beta-1b
* refactored commands

### CODE REVIEW

**Comment by rombert** [comment]
@raducotescu  - curious, why did you add the picocli source code to the project? I would've thought we can pull it in as a Maven dependency. Incidentally, this makes the build fail as the SonarQube plugin chokes on this file.

**Comment by raducotescu** [comment]
@rombert, currently picocli doesn't offer an OSGi friendly bundle. See [0]. I guess I could embed the module for now into the Committer CLI bundle and once picocli provides an OSGi-ready jar we can omit the embed.

[0] - https://github.com/remkop/picocli/issues/734

**Comment by rombert** [comment]
@raducotescu - sounds good to me ! I see your PR has already been merged and

> (...) will be included in the 4.0.0-beta-2 release later this week.

So you can either wait for the release or embed it, it's fine for me either way.

**Comment by raducotescu** [comment]
I'd wait for the release and then merge our PR as well.

**Comment by remkop** [comment]
Picocli [4.0.0-beta-2](https://github.com/remkop/picocli/releases/tag/v4.0.0-beta-2) has been released.

The picocli user manual now has a (very brief) [section](https://picocli.info/#_osgi_bundle) that mentions that the main jar is now an OSGi bundle. If anyone has recommendations to improve the docs, any feedback is welcome!

Enjoy!

**Pull request merged**
